####
# electron-cra-boilerplate 'make' workflow for GitHub actions
#
# This workflow executes on pushing new version tags and will
#
# - Checkout the repository
# - Install NodeJs v16, yarn and project dependencies
# - Build the React app
# - Package the Electron app
# - Make distributables for your application based on your Forge config the Electron app
# - Create build artefacts from make results
#
# @author:  fm-labs <opensource@fmlabs.eu>
# @version: 1
###

name: Make electron app

on:
  push:
    tags:
      - '*'

jobs:
  make:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install yarn
        run: npm install -g yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Create a zip distribution bundle
        run: yarn run make:zip

      - name: Create a deb distribution bundle
        run: yarn run make:deb

      - name: Upload zip bundle as artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-cra-boilerplate-zip
          path: out/make/zip

      - name: Upload deb as artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-cra-boilerplate-deb
          path: out/make/deb
