####
# electron-cra-boilerplate packaging workflow for GitHub actions
#
# This workflow executes on pushing new version tags and will
#
# - Checkout the repository
# - Install NodeJs v16, yarn and project dependencies
# - Build the React app
# - Package the Electron app
# - Create a build artefact from build results
#
# @author:  fm-labs <opensource@fmlabs.eu>
# @version: 1
###

name: Package electron app

on:
  push:
    tags:
      - '*-package'

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Install yarn
        run: npm install -g yarn

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install

      - name: Build the app
        run: yarn run package

      - name: Upload build as artifact
        uses: actions/upload-artifact@v3
        with:
          name: electron-cra-boilerplate-package
          path: out
        #if: ${{ always() }} # Use always() to always run this step to publish test results when there are test failures
